---
title: "HW 07 Part 1"
author: "Christina Beauford"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
```

```{r}
library(GGally)
```
```{r}
library(devtools)
```

```{r}
devtools::install_github("thomasp85/patchwork")
```
```{r}
library(patchwork)
```

#Part one
```{r}
sparrow_raw <- read_tsv("C:/Users/Christina/Documents/BI485/beauford_christina/hw07/sparrows.txt")
```

```{r}
View(sparrow_raw)
```

```{r}
as.tibble(sparrow_raw)
```
```{r}
sparrows <- sparrow_raw %>% 
  mutate(box_group = "Sparrows",
         row_order = 1:nrow(.))
```

```{r}
View(sparrows)
```

#Figure 2
```{r}
plot_box <- sparrows %>% 
  ggplot(aes(x = box_group, 
             y = wingcrd)) +
  geom_boxplot(width = 0.25) +
  labs(x = NULL,
       y = "Wing length (mm)")
```

```{r}
plot_cleveland <- sparrows %>% 
  ggplot(aes(x = wingcrd,
             y = row_order)) +
  geom_point() +
  labs(x = "Wing length (mm)",
       y = "Order of the data")
```

```{r}
plot_box + plot_cleveland
```

```{r}
plot_box + plot_cleveland + coord_flip()
```

##Figure 3
```{r}
plot_box + plot_cleveland + plot_layout(ncol = 1)
```

```{r}
p_culmen <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = culmen)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_culmen
```

```{r}
p_nalospi <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = nalospi)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_nalospi
```

```{r}
p_wt <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wt)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wt
```
```{r}
p_wingcrd <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = wingcrd)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_wingcrd
```
```{r}
p_tarsus <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = tarsus)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_tarsus
```
```{r}
p_head <- sparrows %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = head)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
p_head
```
```{r}
p_culmen + p_nalospi + p_wt + p_wingcrd + p_tarsus + p_head + plot_layout(ncol = 3)
```

nalospi, head, and tarsus appear to have outlier data.

##Figure 5
```{r}
h1 <- sparrows %>%
  filter(Month %in% 6:8) %>% 
  ggplot() +
  geom_histogram(aes(x = wt),
                 binwidth = 0.5,
                 boundary = 0,
                 closed = "right",
                 color = "black") +
  scale_x_continuous(breaks = seq(14, 28, by = 2))
h1
```

```{r}
h2 <- sparrows %>%
  filter(Month %in% 6:8) %>% 
  mutate(Month = case_when(
    Month == 6 ~ "June",
    Month == 7 ~ "July",
    Month == 8 ~ "August")) %>% 
  ggplot() +
  geom_histogram(aes(x = wt),
                 binwidth = 0.5,
                 boundary = 0,
                 color = "black") +
  scale_x_continuous(breaks = seq(14, 28, by = 2)) +
  facet_wrap(~ Month, ncol = 1)
h2
```

```{r}
h1 + h2
```

##Figure 10
```{r}
sparrows %>% ggscatmat(columns = 1:7)
```

##Figure 11
```{r}
month_order = c("May", "June", "July", "August", "September")
sparrows %>% 
  filter(Month %in% 5:9,
         Sex != 0) %>% 
  mutate(Month = case_when(
    Month == 5 ~ "May",
    Month == 6 ~ "June",
    Month == 7 ~ "July",
    Month == 8 ~ "August",
    Month == 9 ~ "September"),
    Month = factor(Month, levels = month_order, ordered = TRUE),
    Sex = ifelse(Sex == 4, "Male", "Female")) %>% 
  ggplot(aes(x = wingcrd,
             y = wt)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  facet_grid(Sex ~ Month)
```




#Part Two
```{r}
crab_raw <- read_csv("C:/Users/Christina/Documents/BI485/beauford_christina/hw07/aegla_crabs.csv")
```
```{r}
crab_raw
```

```{r}
aegla_crabs <- crab_raw %>% 
  select(-c("Site", "AT", "WT", "Shrimp", "Aeglam", "AeglaFe", "AeglaFo")) %>% 
  drop_na(c("N")) %>% 
  mutate(row_order = 1:nrow(.))
aegla_crabs
```

```{r}
depth_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Depth)) 
depth_crab
```


```{r}
width_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Width))
width_crab
```

```{r}
flow_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Flow)) 
flow_crab
```

```{r}
pH_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = pH)) 
pH_crab
```

```{r}
TDS_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = TDS)) 
TDS_crab
```

```{r}
cond_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Cond)) 
cond_crab
```

```{r}
N_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = N)) 
N_crab
```

```{r}
Ni_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Ni)) 
Ni_crab
```

```{r}
phos_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Phos)) 
phos_crab
```

```{r}
Mg_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Mg)) 
Mg_crab
```
```{r}
Ca_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Ca)) 
Ca_crab
```
```{r}
crab_crab <- aegla_crabs %>% 
  ggplot(aes(x = row_order)) +
  geom_boxplot(aes(y = Crab)) 
crab_crab
```

Depth, N, and Phos all have outliers. Phos' outlier is the most significantly different from the rest of the data, though.

##Cleveland Plots

```{r}
width_cleveland <- aegla_crabs %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = Width)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
depth_cleveland <- aegla_crabs %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = Depth)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
Mg_cleveland <- aegla_crabs %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = Mg)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
Cond_cleveland <- aegla_crabs %>% 
  ggplot(aes(y = row_order)) +
  geom_point(aes(x = Cond)) +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
```

```{r}
width_cleveland + depth_cleveland + Mg_cleveland + Cond_cleveland + plot_layout(ncol = 2)
```

##Histograms
```{r}
cond_hist <- aegla_crabs %>%
  ggplot() +
  geom_histogram(aes(x = Cond),
                 bins = 10,
                 binwidth = 1.5,
                 boundary = 0,
                 closed = "right",
                 color = "blue") +
  scale_x_continuous(breaks = seq(0, 85, by = 5))
cond_hist
```
```{r}
TDS_hist <- aegla_crabs %>%
  ggplot() +
  geom_histogram(aes(x = TDS),
                 bins = 20,
                 binwidth = 1,
                 boundary = 0,
                 closed = "right",
                 color = "blue") +
  scale_x_continuous(breaks = seq(0, 40, by = 5))
TDS_hist
```

```{r}
width_hist <- aegla_crabs %>%
  ggplot() +
  geom_histogram(aes(x = Width),
                 bins = 10,
                 binwidth = 1.5,
                 boundary = 0,
                 closed = "right",
                 color = "blue") +
  scale_x_continuous(breaks = seq(0, 12, by = 1))
width_hist
```

##Density
```{r}
cond_density <- aegla_crabs %>% 
  ggplot() +
  geom_density(aes(x = Cond)) +
  scale_x_continuous(breaks = seq(0, 85, by = 5))
cond_density
```

```{r}
TDS_density <- aegla_crabs %>% 
  ggplot() +
  geom_density(aes(x = TDS)) +
  scale_x_continuous(breaks = seq(0, 40, by = 5))
TDS_density
```

```{r}
width_density <- aegla_crabs %>% 
  ggplot() +
  geom_density(aes(x = Width)) +
  scale_x_continuous(breaks = seq(0, 12, by = 1))
width_density
```

```{r}
hist <- cond_hist + TDS_hist + width_hist + plot_layout(ncol = 1)
dens <- cond_density + TDS_density + width_density + plot_layout(ncol = 1)
hist | dens
```

##ggpairs
```{r}
aegla_crabs %>% ggpairs(columns = 1:14)
```

