---
title: "HW 09"
author: "Christina Beauford"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(ggthemes)
```

```{r}
beta_gliadin <- read_lines("C:/Users/Christina/Documents/BI485/beauford_christina/hw09/beta_gliadin.txt", skip = 1)
beta_gliadin
```
```{r}
beta_gliadin2 <- beta_gliadin %>% 
  str_replace_all("\\s", "\\") %>% 
  str_replace_all("\\d", "\\") %>% 
  str_to_upper()
beta_gliadin2
```

```{r}
beta_gliadin3 <- beta_gliadin2 %>% 
  str_c(collapse = "")
beta_gliadin3
str_length(beta_gliadin3)
```

```{r}
str_count(beta_gliadin3, "[^ACGT]")
```
There are 0 charatacters that are not A, C, G, or T.

```{r}
str_count(beta_gliadin3, "ATG")
str_count(beta_gliadin3, "TAA|TGA")
```

66 start; 99 stop codons

```{r}
caat_box <- "CCAAT"
tata_box <- "CTATAA"
str_count(beta_gliadin3, caat_box)
str_count(beta_gliadin3, tata_box)
```


```{r}
caat_seq <- "CCAAT.{100,150}ATG"
str_count(beta_gliadin3, caat_seq)
```

```{r}
tata_seq <- "CTATAA.{50,100}ATG"
str_count(beta_gliadin3, tata_seq)
```

```{r}
caat_seqs_all <- str_extract_all(beta_gliadin3, caat_seq, simplify = TRUE)
str_count(caat_seqs_all)
```

```{r}
str_which(caat_seqs_all, tata_box)
promoter <- str_subset(caat_seqs_all, tata_box)
promoter
str_length(promoter)
```

##Part 2: Ants

```{r}
ants <- read.csv("C:/Users/Christina/Documents/BI485/beauford_christina/hw09/ants.csv")
ants
```
```{r}
library(stringr)
ants2 <- ants %>% 
  select(-c(season, seas.code, trt, plot, sample)) %>% 
  gather(key = species, value = abundance, matches("\\w\\.\\w", ignore.case = FALSE)) %>% 
 mutate(
    species = str_replace(
      species,
      pattern = "(^[A-Z]*\\w{3})\\w{3,}\\.(\\w{4})\\w{2,}",
      replacement = "\\1\\2"),
    year = factor(year, levels = c("2010", "2011"), labels = c("2010", "2011"), ordered = TRUE)) %>% 
  group_by(year, species) %>% 
  summarise(total = sum(abundance, na.rm = TRUE)
  )
ants2
```

```{r}
ggplot(data = ants2, mapping = aes(x = reorder(species, total), y = total, group = species)) + 
  geom_line(color = "gray") +
  geom_point( aes(shape = year), size = 2) +
  coord_flip() +
  labs(x = NULL, y = "Total Abundance", shape = "Year") +
  theme_minimal()
```

```{r}
ants2 %>% 
  filter(total >= 30) %>%  # Arbitrary value
  ggplot(aes(x = year, y = total, group = species)) +
  geom_line(color = "gray") +
  geom_point() +
  theme_classic() + 
  geom_text(data = ants2 %>% 
              filter(year == "2010",
                     total >= 30),
            aes(x = year, 
                y = total, 
                label = species,
                fontface = "italic"),
            hjust = 1.1) +
  geom_text(data = ants2 %>% 
              filter(year == "2011",
                     total >= 30),
            aes(x = year, 
                y = total, 
                label = species,
                fontface = "italic"),
            hjust = -0.1) +
  labs(x = NULL,
       y = "Abundance") +
  theme(legend.position = "none") +
  scale_x_discrete(expand = c(0.2, 0.02))
```


##Part 3: Phlox Flowers
```{r}
flower_size <- read.csv("C:/Users/Christina/Documents/BI485/beauford_christina/hw09/flower_size.csv")
```

```{r}
library(tidyverse)
library(htmlwidgets)
```

```{r}
flowers1 <- flower_size %>%
  filter(!is.na(Flower.number)) %>%
  select(species = Species, cor_length = Corolla.length..cm., throat_width = Corolla.width.throat..cm.) %>% 
   separate(species, into = c("genus", "species"), sep = " ", extra = "drop") %>% 
  group_by(genus, species)%>%
summarize(mean_length = mean(cor_length), mean_width = mean(throat_width), max_length = max(cor_length), max_width = max(throat_width))
flowers1
```

```{r}
pollinators_raw <- read.csv("C:/Users/Christina/Documents/BI485/beauford_christina/hw09/flower_pollinators.csv", na.strings = c("", "NA"))
pollinators_raw
```

```{r}
pollinators1 <- pollinators_raw %>% 
  select(-c(Color, starts_with("Source")))
pollinators1
```
```{r}
pollinators2 <- pollinators1 %>%
  filter(!is.na(Pollinator))
pollinators2
```
```{r}
names(pollinators2) <- c("Species", "Pollinator")
pollinators2
```


```{r}
pollinators <- pollinators2 %>%
  separate(Species, into = c("genus", "species"), sep = " ", extra = "drop")
pollinators
```

```{r}
pollinators <- pollinators %>% 
    separate(Pollinator, into = "Syndrome", sep = " |, ", extra = "drop")
pollinators
```
```{r}
phlox <- inner_join(flowers1, pollinators, by = c("genus", "species"))
phlox
```


```{r}
ggplot(data = phlox) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```
 
```{r}
phlox2 <- phlox %>% 
  mutate(
    Syndrome = str_replace(Syndrome, "bee$", "bees"),
    Syndrome = str_replace(Syndrome, "beetle$", "beetles"))
phlox2
```
 
```{r}
ggplot(data = phlox2) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```
 
```{r}
phlox3 <- phlox2 %>% 
  mutate(
    Syndrome = str_replace(Syndrome, "beetles|flies", "other insects"))
phlox3
```
 
```{r}
ggplot(data = phlox3) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = Syndrome))
```
```{r}
phlox4 <- phlox3 %>% 
  mutate(syndrome_group = case_when(Syndrome == "hummingbird" ~ "Bird",Syndrome == "bat" ~ "Mammal",Syndrome == "autogamous" ~ "Autogamous",TRUE ~ "Insect"))
phlox4
```
 
```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group))
```
```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 color = syndrome_group)) +
#  scale_color_viridis_d(option = "viridis") 
  scale_color_brewer(type = "qual", palette = "Dark2")
```

```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group)) +
  scale_color_viridis_d(option="plasma")
```

```{r}
ggplot(data = phlox4) +
  geom_point(mapping = aes(x = mean_length, y = mean_width, color = syndrome_group)) +
  scale_color_viridis_d(option="inferno")
```

 
```{r}
semo_palette <- c("#C8102E", "#DBE245", "#71C5E8", "#B07C57")

phlox4 %>% 
  ggplot() +
  geom_point(aes(x = mean_length,
                 y = mean_width,
                 shape = syndrome_group,
                 fill = syndrome_group)) +
  scale_shape_manual(values = c(22:25)) +
#  scale_fill_brewer(palette = "Dark2")
#  scale_fill_viridis_d(option = "viridis")
  scale_fill_manual(values = semo_palette)
```
 
```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = mean_length,
                 y = mean_width,
                 shape = syndrome_group,
                 fill = syndrome_group),
             size = 2) +
  labs(shape = "Syndrome",
       fill = "Syndrome",
       x = "Mean Length (cm)",
       y = "Mean Width (cm)") +
  theme_tufte() +
  scale_shape_manual(values = c(22:25)) +
  scale_fill_brewer(palette = "Dark2") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 12))
```

##Part 4: Customized Plots

```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 color = syndrome_group,
                 shape = syndrome_group)) +
  labs(color = "Syndrome",
       fill = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Width (cm)") +
  scale_shape_manual(values = c(20:23)) +
  scale_color_brewer(palette = "Set2")
```
 
```{r}
phlox4 %>% 
 ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 color = syndrome_group,
                 shape = syndrome_group)) +
  labs(color = "Syndrome",
       fill = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Width (cm)") +
  theme_bw() +
  scale_shape_manual(values = c(20:23)) +
  scale_color_viridis_d(option="viridis")
```
 
```{r}
phlox4%>%
  ggplot()+
  geom_point(aes(x = max_length,
                 y = max_width,
                 color = syndrome_group),
             size = 2)+
  labs(color = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Length (cm)")+
  scale_shape_manual(values = c(19:22)) +
  scale_color_brewer(palette = "Set3")
```
 
```{r}
phlox4%>%
  ggplot()+
  geom_point(aes(x = max_length,
                 y = max_width,
                 shape = syndrome_group,
                 color = syndrome_group),
             size=2)+
  labs(shape="Syndrome",
       color = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Length (cm)")+
  scale_shape_manual(values = c(19:22)) +
  scale_color_brewer(palette = "Set1")
```
 
```{r}
phlox4 %>% 
  ggplot() +
  geom_point(aes(x = max_length,
                 y = max_width,
                 color = syndrome_group)) +
  labs(color = "Syndrome",
       fill = "Syndrome",
       x = "Max Length (cm)",
       y = "Max Width (cm)") +
  theme_bw() +
  scale_shape_manual(values = c(20:23)) +
  scale_color_viridis_d(option="viridis")
```
 
 